In [1]:
from collections import deque

graph = {
    'TR': ['TM'],
    'TM': ['TR', 'YS', 'GOA'],
    'YS': ['TM', 'HYD'],
    'GOA': ['TM', 'NAG'],
    'HYD': ['YS', 'WR'],
    'WR': ['HYD', 'BS'],
    'BS': ['WR', 'BBS'],
    'KH': ['BBS', 'HWH','JH'],
    'HWH': ['KH','KOL'],
    'NAG': ['GOA', 'JH'],
    'JH': ['NAG', 'KH'],
    'KH': ['JH', 'HWH', 'KOL'],
    'HWH': ['KH','KOL'],
    'BBS': ['KH', 'BS'],
    'KOL': [],
}

def bfs(graph, start, destination):
    queue = [start]
    visited = set()
    parent = {}

    while queue:
        node = queue.pop(0)
        visited.add(node)

        if node == destination:
            break

        for neighbor in graph[node]:
            if neighbor not in visited:
                queue.append(neighbor)
                parent[neighbor] = node


    path = [destination]
    while path[-1] != start:
        path.append(parent[path[-1]])
    path.reverse()

    return path

start = "TR"
destination = "KOL"
shortest_path = bfs(graph, start, destination)
print("Shortest path:", shortest_path)

Shortest path: ['TR', 'TM', 'GOA', 'NAG', 'JH', 'KH', 'HWH', 'KOL']


In [2]:
graph = {
    'TR': ['TM'],
    'TM': ['TR', 'YS', 'GOA'],
    'YS': ['TM', 'HYD'],
    'GOA': ['TM', 'NAG'],
    'HYD': ['YS', 'WR'],
    'WR': ['HYD', 'BS'],
    'BS': ['WR', 'BBS'],
    'KH': ['BBS', 'HWH', 'JH'],
    'HWH': ['KH', 'KOL'],
    'NAG': ['GOA', 'JH'],
    'JH': ['NAG', 'KH'],
    'KH': ['JH', 'HWH', 'KOL'],
    'HWH': ['KH', 'KOL'],
    'BBS': ['KH', 'BS'],
    'KOL': [],
}

def dfs(graph, start, destination):
    stack = [start]
    visited = set()
    parent = {}

    while stack:
        node = stack.pop()
        visited.add(node)

        if node == destination:
            break

        for neighbor in reversed(graph[node]):
            if neighbor not in visited:
                stack.append(neighbor)
                parent[neighbor] = node

    path = [destination]
    while path[-1] != start:
        path.append(parent[path[-1]])
    path.reverse()

    return path

start = "TR"
destination = "KOL"
shortest_path = dfs(graph, start, destination)
print("Shortest path:", shortest_path)

Shortest path: ['TR', 'TM', 'YS', 'HYD', 'WR', 'BS', 'BBS', 'KH', 'HWH', 'KOL']


In [3]:
from collections import deque

def bfs(graph, start):
    visited = set()
    queue = deque([start])

    while queue:
        vertex = queue.popleft()

        if vertex not in visited:
            print(vertex, end=' ')
            visited.add(vertex)

            queue.extend(neighbor for neighbor in graph[vertex] if neighbor not in visited)

# Example graph represented as an adjacency list
graph = {
    1: [0,3],
    0: [1,3],
    2: [1,4,5,],
    3: [0,1,4],
    4: [3,2,5],
    5: [2,4]
}

# Starting vertex
start_vertex =1

print("BFS Traversal:")
bfs(graph, start_vertex)

BFS Traversal:
1 0 3 4 2 5 

In [4]:
def dfs(graph, start):
    visited = set()
    stack = [start]

    while stack:
        vertex = stack.pop()

        if vertex not in visited:
            print(vertex, end=' ')
            visited.add(vertex)

            stack.extend(neighbor for neighbor in graph[vertex] if neighbor not in visited)

graph = {
    1: [0, 3],
    0: [1, 3],
    2: [1, 4, 5],
    3: [0, 1, 4],
    4: [3, 2, 5],
    5: [2, 4]
}


start_vertex = 1

print("DFS Traversal:")
dfs(graph, start_vertex)


DFS Traversal:
1 3 4 5 2 0 

In [5]:
def dfs(graph, start):
    visited = set()
    stack = [start]

    while stack:
        vertex = stack.pop()

        if vertex not in visited:
            print(vertex, end=' ')
            visited.add(vertex)

            stack.extend(neighbor for neighbor in graph[vertex] if neighbor not in visited)

graph = {
    'B': ['A'],
    'A': ['B', 'S'],
    'S': ['A', 'G','C'],
    'G': ['S','F','H'],
    'H': ['G','E'],
    'E': ['C','H'],
    'C': ['S','F','E','D'],
    'D': ['C'],
    'F': ['G','C'],
}



start_vertex ='B'

print("DFS Traversal:")
dfs(graph, start_vertex)



DFS Traversal:
B A S C D E H G F 

In [6]:
import numpy as np
from heapq import heappop, heappush

def manhattan_distance(state, goal):
    distance = 0
    for i in range(3):
        for j in range(3):
            if state[i, j] != goal[i, j]:
                distance += abs(i - goal[i, j] // 3) + abs(j - goal[i, j] % 3)
    return distance

def a_star(initial_state, goal_state):
    moves = [(-1, 0), (1, 0), (0, -1), (0, 1)]
    priority_queue = [(manhattan_distance(initial_state, goal_state), 0, tuple(map(tuple, initial_state)))]
    visited_states = set()

    while priority_queue:
        _, cost, current_state = heappop(priority_queue)

        if np.array_equal(np.array(current_state), goal_state):
            return cost

        visited_states.add(current_state)

        empty_tile = np.where(np.array(current_state) == 0)
        empty_tile = (empty_tile[0][0], empty_tile[1][0])

        for move in moves:
            new_position = (empty_tile[0] + move[0], empty_tile[1] + move[1])

            if 0 <= new_position[0] < 3 and 0 <= new_position[1] < 3:
                new_state = [list(row) for row in current_state]
                new_state[empty_tile[0]][empty_tile[1]], new_state[new_position[0]][new_position[1]] = \
                    new_state[new_position[0]][new_position[1]], new_state[empty_tile[0]][empty_tile[1]]

                if tuple(map(tuple, new_state)) not in visited_states:
                    new_cost = cost + 1
                    heuristic = new_cost + manhattan_distance(np.array(new_state), goal_state)
                    heappush(priority_queue, (heuristic, new_cost, tuple(map(tuple, new_state))))

    return -1

initial_state = np.array([[2, 8, 3], [1, 6, 4], [7, 0, 5]])
goal_state = np.array([[1, 2, 3], [8, 0, 4], [7, 6, 5]])

result = a_star(initial_state, goal_state)

if result != -1:
    print(f"Minimum cost to reach the goal state: {result}")
    print("\nStep-by-step arrays:")
    current_state = initial_state.copy()
    print(current_state)

    empty_tile = np.where(current_state == 0)
    empty_tile = (empty_tile[0][0], empty_tile[1][0])

    moves = [(-1, 0), (1, 0), (0, -1), (0, 1)]

    for move in moves:
        new_position = (empty_tile[0] + move[0], empty_tile[1] + move[1])

        if 0 <= new_position[0] < 3 and 0 <= new_position[1] < 3:
            new_state = [list(row) for row in current_state]
            new_state[empty_tile[0]][empty_tile[1]], new_state[new_position[0]][new_position[1]] = \
                new_state[new_position[0]][new_position[1]], new_state[empty_tile[0]][empty_tile[1]]

            print("\nMove:")
            print(np.array(new_state))
            current_state = np.array(new_state)
            empty_tile = new_position
else:
    print("No solution found.")


Minimum cost to reach the goal state: 5

Step-by-step arrays:
[[2 8 3]
 [1 6 4]
 [7 0 5]]

Move:
[[2 8 3]
 [1 0 4]
 [7 6 5]]

Move:
[[2 8 3]
 [1 6 4]
 [7 0 5]]

Move:
[[2 8 3]
 [1 6 4]
 [0 7 5]]

Move:
[[2 8 3]
 [1 6 4]
 [7 0 5]]
